-- Pop-method annotations derived from BG Wiki pages on 2026-10-06.
-- These describe how each NM appears; NMWatch does not use them as detection rules.
-- "special" covers weather, events, morphs, assisted spawns, and other nonstandard conditions.
-- Boll Weevil is supplemented from the bundled NM list because BG Wiki has no individual page.
return {
    -- Timed spawns (118)
    ["Ahtu"] = "timed", ["Amanita"] = "timed",
    ["Ancient Goobbue"] = "timed", ["Antican Consul"] = "timed",
    ["Antican Legatus"] = "timed", ["Argus"] = "timed",
    ["Ash Dragon"] = "timed", ["Autarch"] = "timed",
    ["Backoo"] = "timed", ["Bedrock Barry"] = "timed",
    ["Bisque-heeled Sunberry"] = "timed", ["Bo'Who Warmonger"] = "timed",
    ["Boll Weevil"] = "timed", ["Boroka"] = "timed",
    ["Bright-handed Kunberry"] = "timed", ["Bune"] = "timed",
    ["Cactrot Rapido"] = "timed", ["Capricious Cassie"] = "timed",
    ["Carmine Dobsonfly"] = "timed", ["Cemetery Cherry"] = "timed",
    ["Centurio XII-I"] = "timed", ["Cerberus"] = "timed",
    ["Chariotbuster Byakzak"] = "timed", ["Chonchon"] = "timed",
    ["Coo Keja the Unseen"] = "timed", ["Dark Ixion"] = "timed",
    ["Darting Kachaal Ja"] = "timed", ["De'Vyu Headhunter"] = "timed",
    ["Defoliate Leshy"] = "timed", ["Devout Radol Ja"] = "timed",
    ["Diamond Quadav"] = "timed", ["Dirtyhanded Gochakzuk"] = "timed",
    ["Dorgerwor the Astute"] = "timed", ["Dosetsu Tree"] = "timed",
    ["Dragonscaled Bugaal Ja"] = "timed", ["Drexerion the Condemned"] = "timed",
    ["Duke Decapod"] = "timed", ["Duke Haborym"] = "timed",
    ["Dynast Beetle"] = "timed", ["Eba"] = "timed",
    ["Ereshkigal"] = "timed", ["Eyy Mon the Ironbreaker"] = "timed",
    ["Farlarder the Shrewd"] = "timed", ["Father Frost"] = "timed",
    ["Faust"] = "timed", ["Foul Meat"] = "timed",
    ["Fraelissa"] = "timed", ["Ghillie Dhu"] = "timed",
    ["Go'Bhu Gascon"] = "timed", ["Grand Duke Batym"] = "timed",
    ["Guivre"] = "timed", ["Gulool Ja Ja"] = "timed",
    ["Gurfurlur the Menacing"] = "timed", ["Habrok"] = "timed",
    ["Highlander Lizard"] = "timed", ["Hundredfaced Hapool Ja"] = "timed",
    ["Hyakinthos"] = "timed", ["Hydra"] = "timed",
    ["Jormungand"] = "timed", ["Juggler Hecatomb"] = "timed",
    ["King Arthro"] = "timed", ["King Vinegarroon"] = "timed",
    ["Kreutzet"] = "timed", ["Lamina"] = "timed",
    ["Leech King"] = "timed", ["Mahisha"] = "timed",
    ["Maltha"] = "timed", ["Marquis Allocen"] = "timed",
    ["Marquis Amon"] = "timed", ["Medusa"] = "timed",
    ["Meteormauler Zhagtegg"] = "timed", ["Meww the Turtlerider"] = "timed",
    ["Mimas"] = "timed", ["Morbolger"] = "timed",
    ["Mother Globe"] = "timed", ["Mountain Worm"] = "timed",
    ["Mysticmaker Profblix"] = "timed", ["No'Mho Crimsonarmor"] = "timed",
    ["Noble Mold"] = "timed", ["Novv the Whitehearted"] = "timed",
    ["Numbing Norman"] = "timed", ["Ocean Sahagin"] = "timed",
    ["Old Two-Wings"] = "timed", ["Oni Carcass"] = "timed",
    ["Orcish Hexspinner"] = "timed", ["Orcish Overlord"] = "timed",
    ["Orcish Panzer"] = "timed", ["Orcish Warlord"] = "timed",
    ["Padfoot"] = "timed", ["Phanduron the Condemned"] = "timed",
    ["Porphyrion"] = "timed", ["Proconsul XII"] = "timed",
    ["Qu'Vho Deathhurler"] = "timed", ["Quu Xijo the Illusory"] = "timed",
    ["Rambukk"] = "timed", ["Roc"] = "timed",
    ["Rose Garden"] = "timed", ["Serket"] = "timed",
    ["Shikigami Weapon"] = "timed", ["Simurgh"] = "timed",
    ["Skewer Sam"] = "timed", ["Slumbering Samwell"] = "timed",
    ["Snow Maiden"] = "timed", ["Stubborn Dredvodd"] = "timed",
    ["Tiamat"] = "timed", ["Tococo"] = "timed",
    ["Tonberry Decapitator"] = "timed", ["Tonberry Tracker"] = "timed",
    ["Vodyanoi"] = "timed", ["Vrtra"] = "timed",
    ["Wake Warder Wanda"] = "timed", ["Waraxe Beak"] = "timed",
    ["Weeping Willow"] = "timed", ["Woodland Sage"] = "timed",
    ["Xolotl"] = "timed", ["Yagudo Avatar"] = "timed",
    ["Zhuu Buxu the Silent"] = "timed", ["Zipacna"] = "timed",
    -- Lottery spawns (195)
    ["Aiatar"] = "lottery", ["Ambusher Antlion"] = "lottery",
    ["Amemet"] = "lottery", ["Amikiri"] = "lottery",
    ["Antican Magister"] = "lottery", ["Antican Praefectus"] = "lottery",
    ["Antican Proconsul"] = "lottery", ["Antican Tribunus"] = "lottery",
    ["Aquarius"] = "lottery", ["Arachne"] = "lottery",
    ["Arioch"] = "lottery", ["Ashmaker Gotblut"] = "lottery",
    ["Balam-Quitz"] = "lottery", ["Baobhan Sith"] = "lottery",
    ["Baron Vapula"] = "lottery", ["Baronet Romwe"] = "lottery",
    ["Bi'Gho Headtaker"] = "lottery", ["Biast"] = "lottery",
    ["Bigmouth Billy"] = "lottery", ["Bistre-hearted Malberry"] = "lottery",
    ["Black Triple Stars"] = "lottery", ["Bloodpool Vorax"] = "lottery",
    ["Bloodtear Baldurf"] = "lottery", ["Bloodthirster Madkix"] = "lottery",
    ["Bloody Bones"] = "lottery", ["Blubbery Bulge"] = "lottery",
    ["Bluestreak Gyugyuroon"] = "lottery", ["Bomb King"] = "lottery",
    ["Bonnacon"] = "lottery", ["Bu'Ghi Howlblade"] = "lottery",
    ["Buburimboo"] = "lottery", ["Bugbear Strongman"] = "lottery",
    ["Cactuar Cantautor"] = "lottery", ["Cargo Crab Colin"] = "lottery",
    ["Carmine-tailed Janberry"] = "lottery", ["Carnero"] = "lottery",
    ["Celeste-eyed Tozberry"] = "lottery", ["Celphie"] = "lottery",
    ["Centurio X-I"] = "lottery", ["Charybdis"] = "lottery",
    ["Citipati"] = "lottery", ["Count Bifrons"] = "lottery",
    ["Cwn Cyrff"] = "lottery", ["Da'Dha Hundredmask"] = "lottery",
    ["Daggerclaw Dracos"] = "lottery", ["Dame Blanche"] = "lottery",
    ["Deadly Dodo"] = "lottery", ["Demonic Tiphia"] = "lottery",
    ["Despot"] = "lottery", ["Diamond Daig"] = "lottery",
    ["Doppelganger Dio"] = "lottery", ["Doppelganger Gog"] = "lottery",
    ["Drooling Daisy"] = "lottery", ["Dune Widow"] = "lottery",
    ["Dyinyinga"] = "lottery", ["Eastern Shadow"] = "lottery",
    ["Ellyllon"] = "lottery", ["Emergent Elm"] = "lottery",
    ["Energetic Eruca"] = "lottery", ["Enkelados"] = "lottery",
    ["Epialtes"] = "lottery", ["Eurymedon"] = "lottery",
    ["Eurytos"] = "lottery", ["Eyegouger"] = "lottery",
    ["Falcatus Aranei"] = "lottery", ["Flauros"] = "lottery",
    ["Foreseer Oramix"] = "lottery", ["Fradubio"] = "lottery",
    ["Friar Rush"] = "lottery", ["Frostmane"] = "lottery",
    ["Fungus Beetle"] = "lottery", ["Fyuu the Seabellow"] = "lottery",
    ["Ga'Bhu Unvanquished"] = "lottery", ["Gargantua"] = "lottery",
    ["Ge'Dha Evileye"] = "lottery", ["Gloomanita"] = "lottery",
    ["Goblinsavior Heronox"] = "lottery", ["Golden Bat"] = "lottery",
    ["Goliath"] = "lottery", ["Hastatus XI-XII"] = "lottery",
    ["Hawkeyed Dnatbat"] = "lottery", ["Helldiver"] = "lottery",
    ["Hellion"] = "lottery", ["Herbage Hunter"] = "lottery",
    ["Hippolytos"] = "lottery", ["Hoo Mjuu the Torrent"] = "lottery",
    ["Hundredscar Hajwaj"] = "lottery", ["Imdugud"] = "lottery",
    ["Intulo"] = "lottery", ["Ixtab"] = "lottery",
    ["Jaded Jody"] = "lottery", ["Jaggedy-Eared Jack"] = "lottery",
    ["Jailer of Temperance"] = "lottery", ["Jolly Green"] = "lottery",
    ["Keeper of Halidom"] = "lottery", ["Kirata"] = "lottery",
    ["La Velue"] = "lottery", ["Leaping Lizzy"] = "lottery",
    ["Leshonki"] = "lottery", ["Lindwurm"] = "lottery",
    ["Lord of Onzozo"] = "lottery", ["Lumbering Lambert"] = "lottery",
    ["Maighdean Uaine"] = "lottery", ["Manes"] = "lottery",
    ["Masan"] = "lottery", ["Mischievous Micholas"] = "lottery",
    ["Moo Ouzi the Swiftblade"] = "lottery", ["Mouu the Waverider"] = "lottery",
    ["Namtar"] = "lottery", ["Narasimha"] = "lottery",
    ["Nightmare Vase"] = "lottery", ["Nocuous Weapon"] = "lottery",
    ["Northern Shadow"] = "lottery", ["Nue"] = "lottery",
    ["Nunyenunc"] = "lottery", ["Nussknacker"] = "lottery",
    ["Odqan"] = "lottery", ["Ogama"] = "lottery",
    ["Ogygos"] = "lottery", ["Ophion"] = "lottery",
    ["Orctrap"] = "lottery", ["Ose"] = "lottery",
    ["Overlord Bakgodek"] = "lottery", ["Pahh the Gullcaller"] = "lottery",
    ["Panzer Percival"] = "lottery", ["Peallaidh"] = "lottery",
    ["Peg Powler"] = "lottery", ["Pelican"] = "lottery",
    ["Poisonhand Gnadgad"] = "lottery", ["Polybotes"] = "lottery",
    ["Qull the Shellbuster"] = "lottery", ["Quu Domi the Gallant"] = "lottery",
    ["Rampaging Ram"] = "lottery", ["Rhoikos"] = "lottery",
    ["Rhoitos"] = "lottery", ["Sabotender Bailarin"] = "lottery",
    ["Sabotender Bailarina"] = "lottery", ["Sabotender Mariachi"] = "lottery",
    ["Sagittarius X-XIII"] = "lottery", ["Scitalis"] = "lottery",
    ["Sea Hog"] = "lottery", ["Sea Horror"] = "lottery",
    ["Serpopard Ishtar"] = "lottery", ["Serra"] = "lottery",
    ["Sewer Syrup"] = "lottery", ["Seww the Squidlimbed"] = "lottery",
    ["Shadow Eye"] = "lottery", ["Sharp-Eared Ropipi"] = "lottery",
    ["Shii"] = "lottery", ["Soulstealer Skullnix"] = "lottery",
    ["Southern Shadow"] = "lottery", ["Sozu Bliberry"] = "lottery",
    ["Sozu Sarberry"] = "lottery", ["Sozu Terberry"] = "lottery",
    ["Spiny Spipi"] = "lottery", ["Splacknuck"] = "lottery",
    ["Steelbiter Gudrud"] = "lottery", ["Steelfleece Baldarich"] = "lottery",
    ["Stinging Sophie"] = "lottery", ["Stray Mary"] = "lottery",
    ["Swamfisk"] = "lottery", ["Swashstox Beadblinker"] = "lottery",
    ["Tawny-fingered Mugberry"] = "lottery", ["Taxim"] = "lottery",
    ["Teporingo"] = "lottery", ["Thousandarm Deshglesh"] = "lottery",
    ["Tigerbane Bakdak"] = "lottery", ["Tom Tit Tat"] = "lottery",
    ["Tonberry Kinq"] = "lottery", ["Tottering Toby"] = "lottery",
    ["Triarius X-XV"] = "lottery", ["Trickster Kinetix"] = "lottery",
    ["Tumbling Truffle"] = "lottery", ["Tyrannic Tunnok"] = "lottery",
    ["Tzee Xicu the Manifest"] = "lottery", ["Ungur"] = "lottery",
    ["Unut"] = "lottery", ["Valkurm Emperor"] = "lottery",
    ["Viscount Morax"] = "lottery", ["Voll the Sharkfinned"] = "lottery",
    ["Voluptuous Vivian"] = "lottery", ["Vouivre"] = "lottery",
    ["Vuu Puqu the Beguiler"] = "lottery", ["Western Shadow"] = "lottery",
    ["Worr the Clawfisted"] = "lottery", ["Wuur the Sandcomber"] = "lottery",
    ["Wyvernpoacher Drachlox"] = "lottery", ["Yaa Haqa the Profane"] = "lottery",
    ["Yowie"] = "lottery", ["Za'Dha Adamantking"] = "lottery",
    ["Zi'Ghi Boneeater"] = "lottery", ["Zizzy Zillah"] = "lottery",
    ["Zo'Khu Blackcloud"] = "lottery", ["Zoraal Ja's Pkuucha"] = "lottery",
    ["Zuug the Shoreleaper"] = "lottery",
    -- Forced/Quest spawns (75)
    ["Adamantoise"] = "forced/quest", ["Alastor Antlion"] = "forced/quest",
    ["Alkyoneus"] = "forced/quest", ["Aroma Crawler"] = "forced/quest",
    ["Aroma Fly"] = "forced/quest", ["Aroma Leech"] = "forced/quest",
    ["Aspidochelone"] = "forced/quest", ["Awd Goggie"] = "forced/quest",
    ["Balor"] = "forced/quest", ["Beryl-footed Molberry"] = "forced/quest",
    ["Big Bomb"] = "forced/quest", ["Black Coney"] = "forced/quest",
    ["Bomb Queen"] = "forced/quest", ["Brigandish Blade"] = "forced/quest",
    ["Bubbly Bernie"] = "forced/quest", ["Bugbear Matman"] = "forced/quest",
    ["Byakko"] = "forced/quest", ["Caithleann"] = "forced/quest",
    ["Cancer"] = "forced/quest", ["Chocoboleech"] = "forced/quest",
    ["Crimson-toothed Pawberry"] = "forced/quest", ["Crystal Eater"] = "forced/quest",
    ["Death from Above"] = "forced/quest", ["Drone Crawler"] = "forced/quest",
    ["Edacious Opo-opo"] = "forced/quest", ["Fafnir"] = "forced/quest",
    ["Genbu"] = "forced/quest", ["Goblin Archaeologist"] = "forced/quest",
    ["Goblin Collector"] = "forced/quest", ["Goblin Wolfman"] = "forced/quest",
    ["Golden-Tongued Culberry"] = "forced/quest", ["Gration"] = "forced/quest",
    ["Habetrot"] = "forced/quest", ["Hakutaku"] = "forced/quest",
    ["Hercules Beetle"] = "forced/quest", ["Indich"] = "forced/quest",
    ["Jailer of Faith"] = "forced/quest", ["Jailer of Fortitude"] = "forced/quest",
    ["Jailer of Hope"] = "forced/quest", ["Jailer of Justice"] = "forced/quest",
    ["Jailer of Love"] = "forced/quest", ["Jailer of Prudence"] = "forced/quest",
    ["Kirin"] = "forced/quest", ["Kurrea"] = "forced/quest",
    ["Lobais"] = "forced/quest", ["Luaith"] = "forced/quest",
    ["Matron Crawler"] = "forced/quest", ["Morion Worm"] = "forced/quest",
    ["Mycophile"] = "forced/quest", ["Nidhogg"] = "forced/quest",
    ["Nihniknoovi"] = "forced/quest", ["Pallas"] = "forced/quest",
    ["Phantom Worm"] = "forced/quest", ["Queen Crawler"] = "forced/quest",
    ["Sacrificial Goblet"] = "forced/quest", ["Seiryu"] = "forced/quest",
    ["Shen"] = "forced/quest", ["Shieldtrap"] = "forced/quest",
    ["Skull of Envy"] = "forced/quest", ["Skull of Gluttony"] = "forced/quest",
    ["Skull of Greed"] = "forced/quest", ["Skull of Lust"] = "forced/quest",
    ["Skull of Pride"] = "forced/quest", ["Skull of Sloth"] = "forced/quest",
    ["Skull of Wrath"] = "forced/quest", ["Sozu Rogberry"] = "forced/quest",
    ["Suzaku"] = "forced/quest", ["Tarasque"] = "forced/quest",
    ["Tribunus VII-I"] = "forced/quest", ["Ullikummi"] = "forced/quest",
    ["Unstable Cluster"] = "forced/quest", ["Vulkodlac"] = "forced/quest",
    ["White Coney"] = "forced/quest", ["Yara Ma Yha Who"] = "forced/quest",
    ["Ziphius"] = "forced/quest",
    -- Fished spawns (8)
    ["Aipaloovik"] = "fished", ["Cyclopean Conch"] = "fished",
    ["Gugru Orobon"] = "fished", ["Harajnite"] = "fished",
    ["Northern Piranu"] = "fished", ["Orobon"] = "fished",
    ["Proteus"] = "fished", ["Southern Piranu"] = "fished",
    -- Special spawns (39)
    ["Absolute Virtue"] = "special", ["Almighty Apkallu"] = "special",
    ["Asphyxiated Amsel"] = "special", ["Behemoth"] = "special",
    ["Bendigeit Vran"] = "special", ["Blackbeard"] = "special",
    ["Bloodsucker"] = "special", ["Bloody Vrukwuk"] = "special",
    ["Burned Bergmann"] = "special", ["Colorful Leshy"] = "special",
    ["Crushed Krause"] = "special", ["Fogweaver Mozzfuzz"] = "special",
    ["Garfurlar the Rabid"] = "special", ["Garharlor the Unruly"] = "special",
    ["Garhorlur the Brutal"] = "special", ["Geyser Lizard"] = "special",
    ["Giant Orobon"] = "special", ["Guardian Crawler"] = "special",
    ["Haty"] = "special", ["Heliodromos"] = "special",
    ["Ix'aern (MNK)"] = "special", ["Juu Duzu the Whirlwind"] = "special",
    ["King Behemoth"] = "special", ["Kirlirger the Abhorrent"] = "special",
    ["Lich C Magnus"] = "special", ["Lumber Jack"] = "special",
    ["Mee Deggi the Punisher"] = "special", ["Olla Grande"] = "special",
    ["Pulverized Pfeffer"] = "special", ["Ravin Raven"] = "special",
    ["Silverhook"] = "special", ["Smothered Schmidt"] = "special",
    ["Steam Cleaner"] = "special", ["Taisaijin"] = "special",
    ["Tres Duendes"] = "special", ["Upyri"] = "special",
    ["Wounded Wurfel"] = "special", ["Zikko"] = "special",
    ["Zoredonite"] = "special",
}
-- total: 435
