-- Bundled NM name/zone list; exact IDs are verified from BG Wiki page notes.
return {
    spawn_types = require('spawn_types'),
    spawn_details = require('spawn_details'),
    drops = require('drops'),
    normal_drops = require('normal_drops'),
    placeholder_ids = {
        [100] = {[0x126] = "Jaggedy-Eared Jack"}, -- BG Wiki: placeholder ID 126; NM ID 127.
    },
    widescan_placeholders = {
        [2] = { -- Carpenter's Landing, Map 1.
            {nm = "Orctrap", placeholder_name = "Birdtrap", occurrence = "first",
                scope = "scan", after = {name = "Sabertooth Tiger", occurrence = "last"},
                area = "I-9, I-10 (Map 1)"},
        },
        [4] = { -- Bibiki Bay: the sole Eft between the Raven and Marine Dhalmel groups.
            {nm = "Intulo", placeholder_name = "Eft", occurrence = "first", scope = "scan",
                after = {name = "Raven", occurrence = "last"},
                before = {name = "Marine Dhalmel", occurrence = "first"}, area = "H-7"},
        },
        [30] = { -- Riverne - Site #A01: last Flamedrake on the scan list.
            {nm = "Aiatar", placeholder_name = "Flamedrake", occurrence = "last",
                scope = "scan", area = "G-7"},
        },
        [89] = { -- Grauberg [S]: second Ajattara in the first group of two.
            {nm = "Scitalis", placeholder_name = "Ajattara", occurrence = 2,
                group_size = 2, group_occurrence = 1, area = "H-9"},
        },
        [91] = { -- Rolanberry Fields [S]: middle Scabrous Slug in the group of three.
            {nm = "Dyinyinga", placeholder_name = "Scabrous Slug", occurrence = 2,
                group_size = 3, area = "J-9"},
        },
        [98] = { -- Sauromugue Champaign [S]: second of two Lynxes.
            {nm = "Balam-Quitz", placeholder_name = "Lynx", occurrence = 2,
                group_size = 2, area = "K-8"},
        },
        [100] = { -- West Ronfaure: scan group at H-8; lottery area G-9/H-9.
            {nm = "Fungus Beetle", placeholder_name = "Scarab Beetle", occurrence = 2,
                group_size = 3, area = "H-8"},
        },
        [103] = { -- Valkurm Dunes: first of two Giant Bats in the south tunnel.
            {nm = "Golden Bat", placeholder_name = "Giant Bat", occurrence = 1,
                group_size = 2, area = "B-8, C-6, C-7"},
        },
        [105] = { -- Batallia Downs: first sapling in the first of three pairs.
            {nm = "Tottering Toby", placeholder_name = "Stalking Sapling", occurrence = 1,
                group_size = 2, group_occurrence = 1, area = "G-6, G-7"},
        },
        [106] = { -- North Gustaberg [S]: last Coppercap in the five-Coppercap group.
            {nm = "Gloomanita", placeholder_name = "Coppercap", occurrence = 5,
                group_size = 5, area = "H-6"},
        },
        [109] = { -- Pashhow Marshlands: first of five Thread Leeches.
            {nm = "Bloodpool Vorax", placeholder_name = "Thread Leech", occurrence = 1,
                group_size = 5, area = "E-5, F-5"},
        },
        [114] = { -- Eastern Altepa Desert: first of the two Giant Spiders.
            {nm = "Dune Widow", placeholder_name = "Giant Spider", occurrence = 1,
                group_size = 2, area = "G-8"},
        },
        [118] = { -- Buburimu Peninsula: fourth Shoal Pugil in the group of four.
            {nm = "Buburimboo", placeholder_name = "Shoal Pugil", occurrence = 4,
                group_size = 4, area = "K-7"},
        },
        [121] = { -- The Sanctuary of Zi'Tah: lower of two Goobbue Gardeners.
            {nm = "Keeper of Halidom", placeholder_name = "Goobbue Gardener", occurrence = 2,
                group_size = 2, area = "J-7"},
        },
        [123] = { -- Yuhtunga Jungle: last Young Opo-opo in the group of ten.
            {nm = "Mischievous Micholas", placeholder_name = "Young Opo-opo", occurrence = 10,
                group_size = 10, area = "G-9"},
        },
        [125] = { -- Western Altepa Desert: second Cactuar on the scan list.
            {nm = "Cactuar Cantautor", placeholder_name = "Cactuar", occurrence = 2,
                scope = "scan", area = "F-11, G-11"},
        },
        [145] = { -- Giddeus: lower of the two full-time Mendicants.
            {nm = "Hoo Mjuu the Torrent", placeholder_name = "Yagudo Mendicant",
                occurrence = 2, group_size = 2, order = "lower", area = "H-10"},
        },
        [153] = { -- The Boyahda Tree: bottom Death Cap on the scan list.
            {nm = "Ellyllon", placeholder_name = "Death Cap", occurrence = "last",
                scope = "scan", area = "H-11"},
        },
        [160] = { -- Den of Rancor: top of the two Tonberry Beleaguerers.
            {nm = "Bistre-hearted Malberry", placeholder_name = "Tonberry Beleaguerer",
                occurrence = 1, group_size = 2, area = "E-9, E-10, F-9, F-10"},
        },
        [192] = { -- Inner Horutoto Ruins, Map 3: fifth Boggart in the group of six.
            {nm = "Nocuous Weapon", placeholder_name = "Boggart", occurrence = 5,
                group_size = 6, area = "I-9 (Map 3)"},
        },
        [212] = { -- Gustav Tunnel, Map 2: first Goblin Mercenary on the scan list.
            {nm = "Wyvernpoacher Drachlox", placeholder_name = "Goblin Mercenary",
                occurrence = "first", scope = "scan", area = "H-9 (Map 2)"},
        },
    },
    ids = {
        [4] = {[0x02E] = "Serra"},
        [100] = {[0x127] = "Jaggedy-Eared Jack"},
        [101] = {[0x11C] = "Bigmouth Billy"},
        [103] = {[0x14E] = "Valkurm Emperor"},
        [105] = {[0x006] = "Weeping Willow", [0x00C] = "Lumber Jack"},
        [106] = {[0x136] = "Maighdean Uaine", [0x142] = "Maighdean Uaine"},
        [107] = {[0x07D] = "Carnero", [0x08A] = "Carnero", [0x17C] = "Leaping Lizzy", [0x190] = "Leaping Lizzy"},
        [108] = {[0x1A1] = "Bendigeit Vran"},
        [112] = {[0x014] = "Biast"},
        [115] = {[0x105] = "Nunyenunc", [0x14C] = "Numbing Norman"},
        [116] = {[0x131] = "Spiny Spipi"},
        [117] = {[0x073] = "Serpopard Ishtar", [0x0F2] = "Serpopard Ishtar"},
        [118] = {[0x16B] = "Helldiver"},
        [119] = {[0x0B2] = "Daggerclaw Dracos"},
        [120] = {[0x172] = "Roc"},
        [140] = {[0x0AA] = "Thousandarm Deshglesh"},
        [141] = {[0x04C] = "Hundredscar Hajwaj"},
        [145] = {[0x17B] = "Hoo Mjuu the Torrent"},
        [147] = {[0x0EC] = "Zo'Khu Blackcloud"},
        [149] = {[0x02F] = "Hawkeyed Dnatbat"},
        [161] = {[0x0FB] = "Duke Haborym"},
        [167] = {[0x0E6] = "Bloodsucker"},
        [176] = {[0x0BD] = "Seww the Squidlimbed"},
        [195] = {[0x076] = "Cwn Cyrff"},
        [197] = {[0x10E] = "Demonic Tiphia"},
        [198] = {[0x1C2] = "Argus", [0x1CD] = "Leech King"},
        [200] = {[0x130] = "Serket"},
    },
    names = {
        ["al'taieu"] = {"Absolute Virtue", "Jailer of Hope", "Jailer of Justice", "Jailer of Love", "Jailer of Prudence"},
        ["arrapago reef"] = {"Bloody Bones", "Giant Orobon", "Medusa"},
        ["attohwa chasm"] = {"Alastor Antlion", "Ambusher Antlion", "Citipati", "Tiamat", "Xolotl"},
        ["aydeewa subterrane"] = {"Bluestreak Gyugyuroon", "Crystal Eater"},
        ["batallia downs"] = {"Ahtu", "Eyegouger", "Lumber Jack", "Tottering Toby", "Weeping Willow"},
        ["batallia downs [s]"] = {"Dark Ixion", "La Velue"},
        ["beadeaux"] = {"Bi'Gho Headtaker", "Da'Dha Hundredmask", "De'Vyu Headhunter", "Ga'Bhu Unvanquished", "Ge'Dha Evileye", "Go'Bhu Gascon", "Zo'Khu Blackcloud"},
        ["beaucedine glacier"] = {"Gargantua", "Kirata", "Nue"},
        ["behemoth's dominion"] = {"Behemoth", "King Behemoth"},
        ["bhaflau thickets"] = {"Emergent Elm"},
        ["bibiki bay"] = {"Intulo", "Serra", "Shen", "Splacknuck"},
        ["bostaunieux oubliette"] = {"Arioch", "Bloodsucker", "Drexerion the Condemned", "Manes", "Phanduron the Condemned", "Sewer Syrup", "Shii"},
        ["buburimu peninsula"] = {"Backoo", "Buburimboo", "Helldiver", "Wake Warder Wanda"},
        ["caedarva mire"] = {"Peallaidh", "Ravin Raven", "Zikko"},
        ["cape teriggan"] = {"Frostmane", "Kreutzet"},
        ["carpenters' landing"] = {"Hercules Beetle", "Mycophile", "Orctrap"},
        ["castle oztroja"] = {"Mee Deggi the Punisher", "Moo Ouzi the Swiftblade", "Quu Domi the Gallant", "Tzee Xicu the Manifest", "Yaa Haqa the Profane", "Yagudo Avatar"},
        ["castle zvahl baileys"] = {"Duke Haborym", "Grand Duke Batym", "Marquis Allocen", "Marquis Amon"},
        ["castle zvahl keep"] = {"Baron Vapula", "Baronet Romwe", "Count Bifrons", "Viscount Morax"},
        ["crawlers' nest"] = {"Awd Goggie", "Demonic Tiphia", "Drone Crawler", "Dynast Beetle", "Guardian Crawler", "Matron Crawler", "Queen Crawler"},
        ["dangruf wadi"] = {"Chocoboleech", "Geyser Lizard", "Teporingo"},
        ["davoi"] = {"Blubbery Bulge", "Dirtyhanded Gochakzuk", "Hawkeyed Dnatbat", "Poisonhand Gnadgad", "Steelbiter Gudrud", "Tigerbane Bakdak"},
        ["den of rancor"] = {"Bistre-hearted Malberry", "Carmine-tailed Janberry", "Celeste-eyed Tozberry", "Friar Rush", "Hakutaku", "Ogama", "Sozu Bliberry", "Tawny-fingered Mugberry", "Tonberry Decapitator", "Tonberry Tracker"},
        ["dragon's aery"] = {"Fafnir", "Nidhogg"},
        ["east ronfaure"] = {"Bigmouth Billy", "Rambukk", "Swamfisk"},
        ["east ronfaure [s]"] = {"Dark Ixion"},
        ["east sarutabaruta"] = {"Duke Decapod", "Sharp-Eared Ropipi", "Spiny Spipi"},
        ["eastern altepa desert"] = {"Cactrot Rapido", "Centurio XII-I", "Dune Widow"},
        ["fei'yin"] = {"Capricious Cassie", "Eastern Shadow", "Goliath", "Northern Shadow", "Southern Shadow", "Western Shadow"},
        ["fort ghelsba"] = {"Chariotbuster Byakzak", "Hundredscar Hajwaj", "Orcish Panzer"},
        ["fort karugo-narugo [s]"] = {"Dark Ixion"},
        ["garlaige citadel"] = {"Old Two-Wings", "Serket", "Skewer Sam"},
        ["ghelsba outpost"] = {"Bloody Vrukwuk", "Fogweaver Mozzfuzz", "Thousandarm Deshglesh"},
        ["giddeus"] = {"Eyy Mon the Ironbreaker", "Hoo Mjuu the Torrent", "Juu Duzu the Whirlwind", "Quu Xijo the Illusory", "Vuu Puqu the Beguiler", "Zhuu Buxu the Silent"},
        ["grand palace of hu'xzoi"] = {"Ix'aern (MNK)", "Jailer of Temperance"},
        ["grauberg [s]"] = {"Dark Ixion", "Scitalis"},
        ["gusgen mines"] = {"Aroma Fly", "Asphyxiated Amsel", "Burned Bergmann", "Crushed Krause", "Foul Meat", "Juggler Hecatomb", "Pulverized Pfeffer", "Smothered Schmidt", "Wounded Wurfel"},
        ["gustav tunnel"] = {"Amikiri", "Baobhan Sith", "Bune", "Goblinsavior Heronox", "Taxim", "Ungur", "Wyvernpoacher Drachlox"},
        ["halvung"] = {"Big Bomb", "Dorgerwor the Astute", "Farlarder the Shrewd", "Gurfurlur the Menacing", "Kirlirger the Abhorrent"},
        ["ifrit's cauldron"] = {"Ash Dragon", "Bomb Queen", "Foreseer Oramix", "Lindwurm", "Tarasque", "Tyrannic Tunnok", "Vouivre"},
        ["inner horutoto ruins"] = {"Maltha", "Nocuous Weapon"},
        ["jugner forest"] = {"Fradubio", "Fraelissa", "King Arthro", "Meteormauler Zhagtegg", "Panzer Percival"},
        ["jugner forest [s]"] = {"Boll Weevil", "Dark Ixion", "Vulkodlac"},
        ["king ranperre's tomb"] = {"Cemetery Cherry", "Vrtra"},
        ["konschtat highlands"] = {"Bendigeit Vran", "Ghillie Dhu", "Goblin Archaeologist", "Haty", "Highlander Lizard", "Rampaging Ram", "Steelfleece Baldarich", "Stray Mary"},
        ["korroloka tunnel"] = {"Cargo Crab Colin", "Dame Blanche", "Falcatus Aranei", "Morion Worm"},
        ["kuftal tunnel"] = {"Amemet", "Arachne", "Bloodthirster Madkix", "Cancer", "Guivre", "Pelican", "Phantom Worm", "Sabotender Mariachi", "Yowie"},
        ["la theine plateau"] = {"Bloodtear Baldurf", "Goblin Archaeologist", "Lumbering Lambert", "Nihniknoovi", "Slumbering Samwell", "Tumbling Truffle"},
        ["labyrinth of onzozo"] = {"Hellion", "Lord of Onzozo", "Mysticmaker Profblix", "Narasimha", "Ose", "Peg Powler", "Soulstealer Skullnix"},
        ["lower delkfutt's tower"] = {"Epialtes", "Eurymedon", "Hippolytos"},
        ["lufaise meadows"] = {"Colorful Leshy", "Defoliate Leshy", "Kurrea", "Padfoot"},
        ["mamook"] = {"Darting Kachaal Ja", "Devout Radol Ja", "Dragonscaled Bugaal Ja", "Gulool Ja Ja", "Hundredfaced Hapool Ja", "Zizzy Zillah"},
        ["manaclipper"] = {"Cyclopean Conch", "Harajnite", "Zoredonite"},
        ["maze of shakhrami"] = {"Argus", "Aroma Crawler", "Leech King"},
        ["meriphataud mountains"] = {"Chonchon", "Coo Keja the Unseen", "Daggerclaw Dracos", "Waraxe Beak"},
        ["middle delkfutt's tower"] = {"Eurytos", "Ogygos", "Ophion", "Polybotes", "Rhoikos", "Rhoitos"},
        ["misareaux coast"] = {"Gration", "Odqan", "Upyri", "Ziphius"},
        ["monastic cavern"] = {"Orcish Hexspinner", "Orcish Overlord", "Orcish Warlord", "Overlord Bakgodek"},
        ["mount zhayolm"] = {"Cerberus", "Energetic Eruca", "Garfurlar the Rabid", "Garharlor the Unruly", "Garhorlur the Brutal", "Giant Orobon"},
        ["newton movalpolos"] = {"Bugbear Matman", "Goblin Collector", "Swashstox Beadblinker"},
        ["north gustaberg"] = {"Bedrock Barry", "Maighdean Uaine", "Stinging Sophie"},
        ["north gustaberg [s]"] = {"Gloomanita"},
        ["oldton movalpolos"] = {"Bugbear Strongman", "Goblin Wolfman"},
        ["open sea route to al zahbi"] = {"Gugru Orobon", "Northern Piranu", "Orobon", "Southern Piranu"},
        ["open sea route to mhaura"] = {"Gugru Orobon", "Orobon"},
        ["ordelle's caves"] = {"Aroma Leech", "Morbolger"},
        ["outer horutoto ruins"] = {"Bomb King", "Doppelganger Dio", "Doppelganger Gog"},
        ["palborough mines"] = {"Bu'Ghi Howlblade", "No'Mho Crimsonarmor", "Qu'Vho Deathhurler", "Zi'Ghi Boneeater"},
        ["pashhow marshlands"] = {"Bloodpool Vorax", "Bo'Who Warmonger", "Jolly Green"},
        ["phanauet channel"] = {"Aipaloovik", "Stubborn Dredvodd", "Vodyanoi"},
        ["phomiuna aqueducts"] = {"Eba", "Mahisha", "Tres Duendes"},
        ["pso'xja"] = {"Golden-Tongued Culberry"},
        ["qufim island"] = {"Dosetsu Tree", "Trickster Kinetix"},
        ["quicksand caves"] = {"Antican Consul", "Antican Legatus", "Antican Magister", "Antican Praefectus", "Antican Proconsul", "Antican Tribunus", "Centurio X-I", "Diamond Daig", "Hastatus XI-XII", "Nussknacker", "Proconsul XII", "Sabotender Bailarin", "Sabotender Bailarina", "Sagittarius X-XIII", "Triarius X-XV", "Tribunus VII-I"},
        ["qulun dome"] = {"Diamond Quadav", "Za'Dha Adamantking"},
        ["ranguemont pass"] = {"Taisaijin"},
        ["riverne - site #a01"] = {"Aiatar", "Carmine Dobsonfly", "Heliodromos", "Shieldtrap"},
        ["riverne - site #b01"] = {"Boroka", "Imdugud", "Unstable Cluster"},
        ["ro'maeve"] = {"Nightmare Vase", "Shikigami Weapon"},
        ["rolanberry fields"] = {"Black Triple Stars", "Drooling Daisy", "Simurgh"},
        ["rolanberry fields [s]"] = {"Dark Ixion", "Dyinyinga", "Lamina"},
        ["ru'aun gardens"] = {"Byakko", "Despot", "Genbu", "Seiryu", "Suzaku"},
        ["sacrarium"] = {"Balor", "Caithleann", "Indich", "Lobais", "Luaith"},
        ["sauromugue champaign"] = {"Deadly Dodo", "Roc"},
        ["sauromugue champaign [s]"] = {"Balam-Quitz", "Hyakinthos"},
        ["sea serpent grotto"] = {"Charybdis", "Fyuu the Seabellow", "Masan", "Mouu the Waverider", "Namtar", "Novv the Whitehearted", "Ocean Sahagin", "Pahh the Gullcaller", "Qull the Shellbuster", "Sea Hog", "Seww the Squidlimbed", "Voll the Sharkfinned", "Worr the Clawfisted", "Wuur the Sandcomber", "Zuug the Shoreleaper"},
        ["ship bound for mhaura"] = {"Blackbeard", "Sea Horror", "Silverhook"},
        ["silver sea route to al zahbi"] = {"Almighty Apkallu"},
        ["silver sea route to nashmau"] = {"Proteus"},
        ["south gustaberg"] = {"Bubbly Bernie", "Carnero", "Leaping Lizzy", "Tococo"},
        ["tahrongi canyon"] = {"Goblin Archaeologist", "Habrok", "Herbage Hunter", "Serpopard Ishtar", "Yara Ma Yha Who"},
        ["talacca cove"] = {"Giant Orobon"},
        ["temple of uggalepih"] = {"Beryl-footed Molberry", "Crimson-toothed Pawberry", "Death from Above", "Flauros", "Habetrot", "Sacrificial Goblet", "Sozu Rogberry", "Sozu Sarberry", "Sozu Terberry", "Tonberry Kinq"},
        ["the boyahda tree"] = {"Ancient Goobbue", "Aquarius", "Ellyllon", "Leshonki", "Unut", "Voluptuous Vivian"},
        ["the eldieme necropolis"] = {"Cwn Cyrff", "Lich C Magnus", "Skull of Envy", "Skull of Gluttony", "Skull of Greed", "Skull of Lust", "Skull of Pride", "Skull of Sloth", "Skull of Wrath"},
        ["the garden of ru'hmet"] = {"Jailer of Faith", "Jailer of Fortitude"},
        ["the sanctuary of zi'tah"] = {"Keeper of Halidom", "Noble Mold"},
        ["the shrine of ru'avitau"] = {"Faust", "Kirin", "Mother Globe", "Olla Grande", "Ullikummi"},
        ["toraimarai canal"] = {"Oni Carcass"},
        ["uleguerand range"] = {"Black Coney", "Bonnacon", "Father Frost", "Jormungand", "Mountain Worm", "Snow Maiden", "White Coney"},
        ["upper delkfutt's tower"] = {"Alkyoneus", "Autarch", "Enkelados", "Ixtab", "Mimas", "Pallas", "Porphyrion"},
        ["valkurm dunes"] = {"Golden Bat", "Valkurm Emperor"},
        ["valley of sorrows"] = {"Adamantoise", "Aspidochelone"},
        ["ve'lugannon palace"] = {"Brigandish Blade", "Steam Cleaner", "Zipacna"},
        ["wajaom woodlands"] = {"Hydra", "Jaded Jody", "Zoraal Ja's Pkuucha"},
        ["west ronfaure"] = {"Amanita", "Fungus Beetle", "Jaggedy-Eared Jack"},
        ["west sarutabaruta"] = {"Numbing Norman", "Nunyenunc", "Tom Tit Tat"},
        ["west sarutabaruta [s]"] = {"Dark Ixion"},
        ["western altepa desert"] = {"Cactuar Cantautor", "Celphie", "King Vinegarroon"},
        ["xarcabard"] = {"Biast", "Ereshkigal", "Shadow Eye"},
        ["yhoator jungle"] = {"Bisque-heeled Sunberry", "Bright-handed Kunberry", "Edacious Opo-opo", "Woodland Sage"},
        ["yughott grotto"] = {"Ashmaker Gotblut"},
        ["yuhtunga jungle"] = {"Meww the Turtlerider", "Mischievous Micholas", "Rose Garden"},
    },
}
